#-------------------------------
# General Site Settings

title: Sound of AI - A Curriculum on Exploring Human and Machine Audition
logo: logo.png
email: tbd@mit.edu
phone: TBD
address: TBD

menu:
- {name: Curriculum, link: '/curriculum'}
- {name: About, link: '/about'}
- {name: open Sound of AI!, link: 'https://mitmedialab.github.io/prg-extension-boilerplate/machineaudition'}

create-base-url: https://mitmedialab.github.io/prg-extension-boilerplate/machineaudition
projects-base-url: https://soundofai.github.io/projects/

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Sound <br> of AI <br> <font size=6>Making Music with Interactive AI Systems</font>

social:
#- {icon: "ti-facebook", link: "#"}
#- {icon: "ti-instagram", link: "#"}
#- {icon: "ti-dribbble", link: "#"}
#- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  A middle school project-based curriculum about making interactive music generation AI systems.

#  Physical movement is one of the most engaging ways to interact with AI systems, but it’s rare today to see motion integrated with K-12 AI curricula. Beyond that, many middle schoolers have passionate interests in dance, art, physical movement in sports, and video games that involve physical motion (Beat Saber, Just Dance) which aren’t easy to build on in the typical creative learning environments found in classrooms. There is an exciting opportunity to use body movement as an entryway to teaching interesting, less-explored concepts in AI, particularly through active learning by having students design interactions with AI, explore different representations of data, and train image- and pose-recognition models.


#blurb-btn-link: '/about'
#blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"

  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"

  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Design, color: '#fdb157', value: '90%'}
- {name: Logo Design, color: '#9473e6', value: '60%'}
- {name: After Effects, color: '#bdecf6', value: '80%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Learning Approach
experience:
- {name: Flipped Classes, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: UI Design,
    icon: ti-palette,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }
- {
    name: UX Design,
    icon: ti-vector,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: true # Add true to select section
  }
- {
    name: Interaction Design,
    icon: ti-panel,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }

# Curriculum
curriculum-items:
  - title: Audition Overview
    description: Students begin to understand how we use audition in everyday life, and are introduced to the challenges of audition for humans and machines.
    links:
        - name: "Teacher Slides"
          url: "https://docs.google.com/presentation/d/1tOL-PYbXQ8PuaN7Vnrx8nyNYDu-ZFhjYuk9K7eoHioQ/edit?usp=sharing"

  - title: Signals (Pressure Waves)
    description: Students learn about the properties of sound waves and how they impact the music we hear. They focus on the relationship between amplitude and volume, frequency and pitch, and higher harmonics and timbre.
    links:
        - name: "Teacher Slides"
          url: "https://docs.google.com/presentation/d/1rrmhsIJFlbHt89D5iM9nZ-OBn6bBj_bzMhyKazZIRqU/edit?usp=sharing"

    resource_links:
      - name: "Activity: Know Your Dynamics"
        url: "https://mitmedialab.github.io/prg-extension-boilerplate/machineaudition/?project=https://soundofai.github.io/projects/M2.L2%20-%20Know%20Your%20Dynamics.sb3"
      - name: "Activity: Making Melodies"
        url: "https://mitmedialab.github.io/prg-extension-boilerplate/machineaudition/?project=https://soundofai.github.io/projects/M2.L3%20-%20Making%20Melodies.sb3"
      - name: "Activity: Find Your Voice"
        url: "https://mitmedialab.github.io/prg-extension-boilerplate/machineaudition/?project=https://soundofai.github.io/projects/M2.L3%20-%20Find%20your%20Voice.sb3"
      - name: "Activity: What's Your Timbre?"
        url: "https://mitmedialab.github.io/prg-extension-boilerplate/machineaudition/?project=https://soundofai.github.io/projects/M2.L4%20-%20Whats%20your%20Timbre.sb3"
      - name: "Activity: More Bars, More To See"
        url: "https://mitmedialab.github.io/prg-extension-boilerplate/machineaudition/?project=https://soundofai.github.io/projects/M2.L4%20-%20More%20Bars,%20More%20to%20See.sb3"

    images:
        - image: "cat-laptop-train.gif"
          caption: "Training a Teachable Machine Model"
        - image: "dog.gif"
          caption: "Google <br>Teachable Machine"

  - title: Sensation (Ear and Microphones)
    description: Students learn about the mechanics of audition in both humans and machines, including the anatomy of the human ear and the hardware design of microphones.


  - title: Perception (Brain and Computer)
    description: Students focus on the ways in which the human brain processes sound, and how computers use different data representations to understand the sounds they hear.


  - title: Human-AI Collaboration
    description: Students gain confidence and understanding through a CAPstone project in which they design a human-AI collaborative music generation program.

course-wide-materials:
  - name: "Student Journal"
    url: "https://docs.google.com/presentation/d/1ILgv4ImxyDEvrME0M3CViTqjApBKO4nLvuy0VV02XWg/edit"
  - name: "Scaffolding Cards"
    url: "https://tinyurl.com/dwai-codingcards"
  - name: "Standards"
    url: "https://docs.google.com/document/d/15ba3GB6g1GHxJ40YV0NFAYz__GG2kpIs2OBrZXbKgMw/edit?usp=sharing"

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
# TODO: maybe just collect these from curriculum days? or feature just a few :D
all-projects:
  - image: "shydog.gif"
    url: "projects/M2.L2 - Know Your Dynamics.sb3"
  - image: "circle-drawing.gif"
    url: "projects/M2.L3 - Find your Voice.sb3"
  - image: "hand-spray-paint.gif"
    url: "projects/M2.L3 - Making Melodies.sb3"
  - image: "be-a-pirate.gif"
    url: "Pirate Face.sb3"
  - image: "EmotionJellyfish.gif"
    url: "EmotionJellyfish.sb3"
    gfycat: "GlossyUnripeFireant"

portfolio-home-items:
  - image : "assets/images/dancing-with-ai/draw-yellow-circles.png"
    url: "#"
  - image : "assets/images/dancing-with-ai/jenna-dog-hide.gif"
    url: "#"
  - image : "assets/images/dancing-with-ai/emotion-face.png"
    url: "#"

# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"

  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
